# Generated by Django 3.0.8 on 2020-07-16 17:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timesheetdj', '0002_persoana'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domeniu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Locatie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Obiect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='activitate',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='persoana',
            name='published_date',
        ),
        migrations.CreateModel(
            name='Actiune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('domeniu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheetdj.Domeniu')),
            ],
        ),
        migrations.AddField(
            model_name='activitate',
            name='actiune',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timesheetdj.Actiune'),
        ),
        migrations.AddField(
            model_name='activitate',
            name='obiect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timesheetdj.Obiect'),
        ),
    ]
